# Generated by Django 5.1.2 on 2024-10-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=128, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movie_app.moviegenre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(height_field='poster_height', upload_to='posters', width_field='poster_width')),
                ('poster_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poster_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, help_text='in kilobytes')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='movie_app.movie')),
            ],
        ),
    ]
