# Generated by Django 5.1.2 on 2024-10-29 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_showtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie_app.showtime')),
            ],
        ),
    ]
